EPOCHS: 4
batches_per_epoch: 10
latent_dim: 32
rate: 0.0
mlp_dims: [256, 128, 64]
ner_lr: 0.001
kl_lr: 0.001
label_distribution: [0.0, 0.8468, 0.0430, 0.0153, 0.0327, 0.0352, 0.0256, 0.0007, 0.0002, 0.0005]
model_start_weights_filename: 'BERT_NER_final'
model_save_weights_name: 'BERT_NER_data_dist_kl'
